#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 $POSTGRES_DB $POSTGRES_USER <<-SQL
    CREATE ROLE ${DB_USERNAME_USER_SERVICE} LOGIN;
    CREATE SCHEMA user_schema AUTHORIZATION ${DB_USERNAME_USER_SERVICE};
    ALTER ROLE ${DB_USERNAME_USER_SERVICE} SET search_path = user_schema;

    CREATE ROLE ${DB_USERNAME_QUEST_SERVICE} LOGIN;
    CREATE SCHEMA quest_schema AUTHORIZATION ${DB_USERNAME_QUEST_SERVICE};
    ALTER ROLE ${DB_USERNAME_QUEST_SERVICE} SET search_path = quest_schema;

    CREATE ROLE ${DB_USERNAME_PROGRESSION_SERVICE} LOGIN;
    CREATE SCHEMA progression_schema AUTHORIZATION ${DB_USERNAME_PROGRESSION_SERVICE};
    ALTER ROLE ${DB_USERNAME_PROGRESSION_SERVICE} SET search_path = progression_schema;
SQL

psql -v ON_ERROR_STOP=1 $POSTGRES_DB $POSTGRES_USER <<-SQL
    ALTER ROLE ${DB_USERNAME_USER_SERVICE} PASSWORD '${DB_PASSWORD_USER_SERVICE}';
    ALTER ROLE ${DB_USERNAME_QUEST_SERVICE} PASSWORD '${DB_PASSWORD_QUEST_SERVICE}';
    ALTER ROLE ${DB_USERNAME_PROGRESSION_SERVICE} PASSWORD '${DB_PASSWORD_PROGRESSION_SERVICE}';
SQL
